### ISSUE TITLE
CircularDependencyException when using ManyToMany + OneToMany / ManyToOne

### ISSUE THREAD

**Issue by lsgpimentel** [jhipster/jhipster-uml#171]
### The issue

Happens when I use a ManyToMany and a OneToMany or ManyToOne relationship that connects the same two entities in both.

---
#### The stacktrace

```
An error has occurred:
	CircularDependencyException
Error message:
	There is a circular dependency in the model.
The processed entities so far: [ No entity could have been handled. ]
The elements that still needed processing: [ Source entity: User, destination entity: Survey, cardinality: many-to-many,Source entity: User, destination entity: Survey, cardinality: one-to-many ].
Stack trace:
Error
    at Object.<anonymous> (/usr/lib/node_modules/jhipster-uml/lib/exceptions/circular_dependency_exception.js:7:41)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/jhipster-uml/lib/scheduler.js:6:35)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

```

---

### The XMI or JDL file

```
entity User {
}
entity Survey {

}
relationship ManyToMany {
  User{answeredSurveys} to Survey{participants}
}
relationship OneToMany {
  User to Survey{creator}
}
```

---

### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `2.27.2` | `1.6.4` |

**Comment by MathieuAA** [comment]
I'll test it tonight and keep this thread updated.

**Comment by MathieuAA** [comment]
Your example doesn't seem to work with JHipster... Can you drop an issue in their issue tracker?

**Comment by lsgpimentel** [comment]
How are you testing this?
I'm having no problem using:

```
 $ cat Survey.json 
{
    "relationships": [
        {
            "relationshipName": "participants",
            "otherEntityName": "user",
            "relationshipType": "many-to-many",
            "otherEntityField": "id",
            "ownerSide": true
        },
        {
            "relationshipName": "creator",
            "otherEntityName": "user",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "survey"
        }
    ],
    "fields": [],
    "changelogDate": "20160324221126",
    "dto": "no",
    "service": "no",
    "entityTableName": "survey",
    "pagination": "no"
}
```

```
 $ cat User.json 
{
    "relationships": [],
    "fields": [],
    "changelogDate": "20160324220606",
    "dto": "no",
    "service": "no",
    "entityTableName": "user",
    "pagination": "no"
}
```

**Comment by lsgpimentel** [comment]
My guess, by looking very briefly to the code, is that the `removeClassFromPool` method in `ClassScheduler` is assuming that the entity will not be used in another relationship, incorrectly removing it from the pool.

**Comment by MathieuAA** [comment]
I tested the case by generating the entities with the questions. Moreover, your pasted JSON doesn't correspond to your JDL (`"ownerSide": true`).

**Comment by lsgpimentel** [comment]
@MathieuAA,

Setting the `ownerSide` to `false` does not change anything here. I tried to regenerate the same entity and to create another one (results below).
Can you paste your JSON, please?

```
 $ yo jhipster:entity test

Just found a `.yo-rc.json` in a parent directory.

The entity test is being created.


Generating field #1

? Do you want to add a field to your entity? No

Generating relationships to other entities

? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? User
? What is the name of the relationship? bla1
? What is the type of the relationship? many-to-many
? Is this entity the owner of the relationship? No
? What is the name of this relationship in the other entity? bla2

================= Test =================
Relationships
bla1 (User) many-to-many


Generating relationships to other entities

? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? User
? What is the name of the relationship? bla3
? What is the type of the relationship? many-to-one
? When you display this relationship with AngularJS, which field from 'User' do you want to use? id

================= Test =================
Relationships
bla1 (User) many-to-many
bla3 (User) many-to-one


Generating relationships to other entities

? Do you want to add a relationship to another entity? No

================= Test =================
Relationships
bla1 (User) many-to-many
bla3 (User) many-to-one



? Do you want to use a Data Transfer Object (DTO)? No, use the entity directly
? Do you want to use separate service class for your business logic? No, the REST controller should use the repository directly
? Do you want pagination on your entity? No

Everything is configured, generating the entity...

   create .jhipster/Test.json
   create src/main/java/com/mycompany/myapp/domain/Test.java
   create src/main/java/com/mycompany/myapp/repository/TestRepository.java
   create src/main/java/com/mycompany/myapp/web/rest/TestResource.java
   create src/main/resources/config/liquibase/changelog/20160325114454_added_entity_Test.xml
 conflict src/main/resources/config/liquibase/master.xml
? Overwrite src/main/resources/config/liquibase/master.xml? overwrite this and all others
    force src/main/resources/config/liquibase/master.xml
   create src/main/webapp/app/entities/test/tests.html
   create src/main/webapp/app/entities/test/test-detail.html
   create src/main/webapp/app/entities/test/test-dialog.html
   create src/main/webapp/app/entities/test/test-delete-dialog.html
    force src/main/webapp/app/layouts/navbar/navbar.html
   create src/main/webapp/app/entities/test/test.state.js
   create src/main/webapp/app/entities/test/test.controller.js
   create src/main/webapp/app/entities/test/test-dialog.controller.js
   create src/main/webapp/app/entities/test/test-delete-dialog.controller.js
   create src/main/webapp/app/entities/test/test-detail.controller.js
   create src/main/webapp/app/entities/test/test.service.js
   create src/test/javascript/spec/app/entities/test/test-detail.controller.spec.js
   create src/test/java/com/mycompany/myapp/web/rest/TestResourceIntTest.java

Running gulp Inject to add javascript to index

[08:44:58] Using gulpfile ~/workspace_eclipse/test/gulpfile.js
[08:44:58] Starting 'inject'...
[08:44:59] gulp-inject 104 files into index.html.
[08:44:59] Finished 'inject' after 138 ms
```




```
 $ cat Test.json 
{
    "relationships": [
        {
            "relationshipName": "bla1",
            "otherEntityName": "user",
            "relationshipType": "many-to-many",
            "ownerSide": false,
            "otherEntityRelationshipName": "bla2"
        },
        {
            "relationshipName": "bla3",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [],
    "changelogDate": "20160325114454",
    "dto": "no",
    "service": "no",
    "entityTableName": "test",
    "pagination": "no"
}

$ cat User.json 
{
    "relationships": [],
    "fields": [],
    "changelogDate": "20160324220606",
    "dto": "no",
    "service": "no",
    "entityTableName": "user",
    "pagination": "no"
}

```

**Comment by MathieuAA** [comment]
When I say fail, I mean when I'm `mvn test`-ing it, it fails. That's how I test everything that comes out of JHipster UML.
But again, I may be wrong. I'll test it again in a few minutes.

**Comment by MathieuAA** [comment]
Well, this is getting more and more interesting =)

Here's what I did:

```
yo jhipster:entity Survey

The entity Survey is being created.


Generating field #1

? Do you want to add a field to your entity? No

Generating relationships to other entities

? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? User
? What is the name of the relationship? participant
? What is the type of the relationship? many-to-many
? Is this entity the owner of the relationship? No
? What is the name of this relationship in the other entity? answeredSurvey

================= Survey =================
Relationships
participant (User) many-to-many


Generating relationships to other entities

? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? User
? What is the name of the relationship? creator
? What is the type of the relationship? many-to-one
? When you display this relationship with AngularJS, which field from 'User' do ? When you display this relationship with AngularJS, which field from 'User' do you want to use? id

================= Survey =================
Relationships
participant (User) many-to-many
creator (User) many-to-one


Generating relationships to other entities

? Do you want to add a relationship to another entity? No

================= Survey =================
Relationships
participant (User) many-to-many
creator (User) many-to-one
```

The JSON:

```
{
    "relationships": [
        {
            "relationshipName": "participant",
            "otherEntityName": "user",
            "relationshipType": "many-to-many",
            "ownerSide": false,
            "otherEntityRelationshipName": "answeredSurvey"
        },
        {
            "relationshipName": "creator",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [],
    "changelogDate": "20160325225139",
    "dto": "no",
    "service": "no",
    "entityTableName": "survey",
    "pagination": "no"
}
```

`mvn test` fails.

I then proceeded with the second part of my test, generating everything with JHipster UML.

```
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipType": "many-to-many",
      "relationshipName": "participants",
      "otherEntityName": "user",
      "ownerSide": false,
      "otherEntityRelationshipName": "answeredSurveys"
    },
    {
      "relationshipId": 2,
      "relationshipType": "many-to-one",
      "relationshipName": "creator",
      "otherEntityName": "user",
      "otherEntityField": "id"
    }
  ],
  "fields": [],
  "changelogDate": "20160325233112",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "entityTableName": "survey"
}
```

There is a a bug with the scheduler, I give you that. 
The generated JSON is valid though. I've just pushed a fix for the scheduler, now I don't know how you got your project to pass the tests but the tests don't pass with the original JDL.

**Comment by lsgpimentel** [comment]
I have not tested your fix, but I don't think it will solve the problem at all. It's not related to the `User` entity specifically.
You can use the JDL below and you will get the same error:
```
entity A {
}
entity B {
}
relationship ManyToMany {
  A{creator} to B
}
relationship ManyToMany {
  B to A{participants}
}
```

There's really a problem with this "pool thing". Like I said before, my guess is that the entities are being remove from the pool after their first use. When you try to use the same entity in other relationships, you can't :/. In the next iteration, since you have no entity to remove, then `previousCount === this.pool.length` returns `true`.

My `mvn test` are, in fact, failing, but it's related to another problem, which I'm investigating before creating an issue in generator-jhipster. Just for reference, it's something like:
```
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.mycompany.myapp.domain.User.drawingss in com.mycompany.myapp.domain.Drawing.participantss
	at org.hibernate.cfg.annotations.CollectionBinder.bindStarToManySecondPass(CollectionBinder.java:769)
	at org.hibernate.cfg.annotations.CollectionBinder$1.secondPass(CollectionBinder.java:729)
	at org.hibernate.cfg.CollectionSecondPass.doSecondPass(CollectionSecondPass.java:70)
	at org.hibernate.cfg.Configuration.originalSecondPassCompile(Configuration.java:1697)
	at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1426)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857)
	... 50 common frames omitted
```


----------

**Off-topic:**
IMHO, this hole scheduler thing is unnecessary. Why not let the user order the entities and relationships correctly, like we all need to do with SQL when creating tables and FK's? It's just awkward to me that a completely disorganized JDL just works.
Nevertheless, I find the current solution a bit confusing. Here's my 2 cents on how I would do it:
1. Separate the entities from the relationships (2 different arrays);
2. Validate what you need to validate;
3. Generate the JSON of the entities (no relationships yet);
4. Generate the JSON of the relationships. For each entity, iterate all relationships testing if the source or destination are about the current entity;
4. Merge JSON of entities with JSON of relationships;
5. Write the JSON's to disk;
6. Call `yo jhipster:entity`;

Hope it helps!

**Comment by MathieuAA** [comment]
Hi, in this case there is a circular dependency, and it's normal.

In order to have a Many-to-Many between A and B, B must first be generated. However, if there's Many-to-Many between B and A (the order is important), A must first be generated. That's why there is problem.

**Comment by MathieuAA** [comment]
I am not generating relationships in the order of their declaration. I have to maintain database coherence in the end.

**Comment by lsgpimentel** [comment]
Ohh, sorry, I just pasted it wrong, consider the below:
```
entity A {
}
entity B {
}
relationship ManyToOne {
  A{creator} to B
}
relationship ManyToMany {
  B to A{participants}
}
```

The bug is still there.

**Comment by MathieuAA** [comment]
Ah! But your ManyToMany relationship must be bidirectional. I wonder if it's supported by JHipster and not in the doc. **Gotta test**. If it's supported, I'll allow in JHipster UML right away!

Moreover, JHipster has been known to have some issues with multiple relationships coming from and going to the same 2 entities... I wonder if you've actually found a bug.

I've given much thought about that, and (personnally) I'd do it like you said. Let the user fail.
But this isn't really user-friendly... 
What if the user has a huge data model? I don't think he/she would like it to just have to worry about order... and the algorithm is really simple.
Your solution has been considered once, but not considered because of a few problems:
  - If the user has 3 entities, yo jhipster:entity MyEntity[1..3] would be called 6 times, and that's ok.. but if the user has 30 entities (a very common case, but it's always way more than that) it's not acceptable;
  - We don't generate entities, we let JHipster do it because JHipster has some internal mechanisms to detect faulty JSON files and we don't host any template in this project for the sake of atomicity and no-redundancy. So we'd actually have to rely on JHipster the double amount of times for one task.

But again, nothing definitive and unchanging, and I'm still trying to find better solutions to problems.
I'll test your solution in a separate branch. If it's actually better than ours, then I'll add.
Thanks for the suggestion!

**Comment by MathieuAA** [comment]
Update: I've created an issue for your suggestion, further talk about this should be done in #174 now.

**Comment by lsgpimentel** [comment]
Even if it's bidirectional the error will persist.

We continue the other discussion in #174.

**Comment by MathieuAA** [comment]
It's normal there is a circular dependency.
The Many-to-One needs the destination to be generated first.
The Many-to-Many needs the destination too to be generated first.
As the MtO's destination and MtM's source are not the same...
However, if you write
```
entity A {
}
entity B {
}
relationship OneToMany {
  A{creator} to B
}
relationship ManyToMany {
  B{a} to A{participants}
}
```
then the generation will be done. And the test will pass.
The One-to-One, the Many-to-Many and the Many-to-One need the destination to be scheduled first.
Only the One-to-Many needs the source to be scheduled first.

I hope I'm clear enough... I know this can be painful at first =/

**Comment by lsgpimentel** [comment]
Yes, I got it. =]
In the end, you can't run off this kind of thing, even with the ordering. But if you can, for each entity, generate 2 database changelogs (like you already suggested), this won't be problem. Anyway, this should be discussed in #174.

**Comment by MathieuAA** [comment]
By the way, should we close this thread? I don't like closing them if there's still some problem/question pending.

**Comment by lsgpimentel** [comment]
I think we should, since you created #174. But that is up to you. ;)
